steps:
  # Run tests
  - name: 'mcr.microsoft.com/dotnet/sdk:5.0-focal'
    entrypoint: 'dotnet'
    args: ['test']
    waitFor: ['-']
    id: 'test'
    
# Build the container image (Encoder)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile' ,'-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BRANCH_NAME', '.']
    waitFor: ['-']
    id: 'build-image'

# Push the container image to Container Registry (Encoder)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BRANCH_NAME']
    waitFor: ['build-image','test']
    id: 'push-image'
    
# Deploy container image to Cloud Run (viewer)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', '$_SERVICE_NAME', 
           '--image', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BRANCH_NAME', 
           '--region', 'europe-west4', 
           '--platform', 'managed', 
           '--memory', '2Gi',
           '--timeout','5m',
           '--service-account', '$_SA',
           '--allow-unauthenticated'
    ]
    waitFor: ['push-image']
    
images:
  - gcr.io/$PROJECT_ID/$_IMAGE_NAME
